# -*- coding: utf-8 -*-
"""assigment no 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PROTxrJ-3FHmD8_3wvqNc5jWetkMDVGK
"""

age_list=(24,25,26,27,28)

print(age_list)

name_list = ["barani","guna","akilesh","prakash","shrushma"]

print(type(name_list))

name_list.append("yazhini")

print(name_list)

age_list = list(age_list)

age_list.append(30,)

print(age_list)

name_list.remove("yazhini")

print(name_list)

age_list.pop(5)

age_list.extend([29,30,26])

print(age_list)

age_list.sort(reverse=True)

print(age_list)

max(age_list)

min(age_list)

sum(age_list)

original=age_list
age_copy_list=original.copy()
print(age_copy_list)

print(age_list)

"""--accessing list element--"""

age_list.clear()

print(name_list[2:5])

print(name_list[1:])

print(name_list[0:3])

name_list.reverse()

print(name_list)

list_dup = [1, 2, 1, 1, 3, 1, 2, 5, 9, 1]

list_dup.count(1)

len(list_dup)

"""dictionary"""

stundent_mark = [{"name":["barani","balaji","kishore","prakash","shrushma"] ,"mark":[99,45,34,1,100]}]

print(stundent_mark)

print(type(stundent_mark))

print(stundent_mark)

print(stundent_mark.keys())